<div class="row">

    <?php if ($this->posts->count() > 0) : ?>
        <?php foreach ($this->posts as $post): ?>

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="<?= $this->url('post', array('slug' => $post->slug)); ?>"><?= $post->name; ?></a></h3>
                    </div>
                    <div class="panel-body">
                        <?= $post->content; ?>
                    </div>
                    <?php if ($post->hasTags()) : ?>
                        <div class="panel-footer">
                            Tags : <?= $post->tagsList()?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

        <?php endforeach; ?>
    <?php endif; ?>

</div>